### ISSUE TITLE
Проверить работу запроса по получению данных аккаунта из БД

### ISSUE THREAD

**Issue by anst-foto** [itstep-shambala/Account#16]
После слияния #13 неправильно вносятся данные в модель

**Comment by GreyMiller13** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Внести изменения в модели данных](https://trello.com/c/KGsFSQ3R/10-%D0%B2%D0%BD%D0%B5%D1%81%D1%82%D0%B8-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B2-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B8-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85)
